[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { git = "https://github.com/yewstack/yew/" }
reqwasm = { version = "0.4", features = ["json"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
wasm-bindgen = "0.2.78"
gloo = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
monaco = { git = "https://github.com/hamza1311/rust-monaco", branch = "yew-playground", features = ["yew-components"] }
bson = "2.1"
getrandom = { version = "*",  features = ["js"]}
uuid = { version = "0.8.1", features = ["serde", "v4", "wasm-bindgen"] }

[dependencies.web-sys]
version = "0.3"
features = [
    "HtmlIFrameElement",
    "HtmlDocument"
]
