[workspace]
members = [
    "services/app-compiler",
    "services/backend",
    "services/common",
    "frontend",
]
exclude = [
    "app" # app must NOT be part of the workspace. It needs to have it's own target directory and lock file
]
