name: Test & Build
on:
  push:
    branches: [ master ]

jobs:
  app:
    name: Build and publish app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: app
          push: true
          tags: ghcr.io/hamza1311/yew-playground-app:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  backend:
    name: Build & publish backend
    runs-on: ubuntu-latest
    needs:
      - app
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: ghcr.io/hamza1311/yew-playground:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
